# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  database: chasing_pictures_development
  host: localhost
  pool: 5
  username: chasing_pictures
  password: yay

test:
  adapter: postgresql
  database: chasing_pictures_test
  pool: 5
  username: chasing_pictures
  password: yay

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
